---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          resources:
            limits:
              memory: 150Mi
          volumeMounts:
            - mountPath: /data
              name: data
          env:
            - name: POSTGRES_DB
              value: quarkus
            - name: POSTGRES_USER
              value: quarkus
            - name: POSTGRES_PASSWORD
              value: quarkus
            - name: PGDATA
              value: /data/pgdata
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - port: 2181
  selector:
    app: zookeeper
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - image: quay.io/strimzi/kafka:latest-kafka-3.6.0
          name: zookeeper
          command: ["sh", "-c", "bin/zookeeper-server-start.sh config/zookeeper.properties"]
          resources:
            limits:
              memory: 128Mi
          env:
            - name: LOG_DIR
              value: /tmp/logs
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"zookeeper"}]'
spec:
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: quay.io/strimzi/kafka:latest-kafka-3.6.0
          name: kafka
          command: ["sh", "-c",
            "bin/kafka-server-start.sh config/server.properties \
                  --override listeners=$KAFKA_LISTENERS \
                  --override advertised.listeners=$KAFKA_ADVERTISED_LISTENERS \
                  --override zookeeper.connect=zookeeper:2181"]
          env:
            - name: LOG_DIR
              value: /tmp/logs
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181

